### ISSUE TITLE
emm，这是一种什么情况，该怎么做呢

### ISSUE THREAD

**Issue by Frandore** [yeskn-studio/vmoex-framework#10]
![image](https://user-images.githubusercontent.com/43910740/55089530-84134180-50e8-11e9-9274-56497dfc05a0.png)

**Comment by Jaggle** [comment]
这是执行什么操作？

**Comment by Frandore** [comment]
> 这是执行什么操作？

php bin/console translation:persist时候的错误，

**Comment by Jaggle** [comment]
在这之前还有两个命令没执行，具体看安装文档

**Comment by Frandore** [comment]
> 在这之前还有两个命令没执行，具体看安装文档

是按步执行的...然后报错了

**Comment by Jaggle** [comment]
执行一下这个命令试试(webuser为你的web用户)：

```
sudo -u <webuser>  php bin/console doctrine:cache:clear-metadata
```

**Comment by Frandore** [comment]
我拿宝塔重装了一遍了.....现在是这个猫饼，在创建静态资源文件的时候，![image](https://user-images.githubusercontent.com/43910740/55233437-9cf43200-5263-11e9-824e-9b5a66b5941b.png)

**Comment by Frandore** [comment]
这红的我眼瞎了

**Comment by Frandore** [comment]
> 执行一下这个命令试试(webuser为你的web用户)：
> 
> ```
> sudo -u <webuser>  php bin/console doctrine:cache:clear-metadata
> ```
  An error occurred while running:                                                                                      
  '/www/server/nvm/versions/node/v10.15.3/bin/node' '/www/server/nvm/versions/node/v10.15.3/bin/uglifyjs' '-o' '/tmp/a  
  ssetic_uglifyjs2_outN9DyBc' '/tmp/assetic_uglifyjs2_inSZKe4D'                                                         
                                                                                                                        
  Error Output:                                                                                                         
  Parse error at /tmp/assetic_uglifyjs2_inSZKe4D:45,4                                                                   
      const self = window.YesknPlugins;                                                                                 
      ^                                                                                                                 
  ERROR: Unexpected token: keyword «const»                                                                              
      at JS_Parse_Error.get (eval at <anonymous> (/www/server/nvm/versions/node/v10.15.3/lib/node_modules/uglify-js/to  
  ols/node.js:20:1), <anonymous>:71:23)                                                                                 
      at fatal (/www/server/nvm/versions/node/v10.15.3/lib/node_modules/uglify-js/bin/uglifyjs:296:53)                  
      at run (/www/server/nvm/versions/node/v10.15.3/lib/node_modules/uglify-js/bin/uglifyjs:240:9)                     
      at Object.<anonymous> (/www/server/nvm/versions/node/v10.15.3/lib/node_modules/uglify-js/bin/uglifyjs:165:5)      
      at Module._compile (internal/modules/cjs/loader.js:701:30)                                                        
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)                                          
      at Module.load (internal/modules/cjs/loader.js:600:32)                                                            
      at tryModuleLoad (internal/modules/cjs/loader.js:539:12)                                                          
      at Function.Module._load (internal/modules/cjs/loader.js:531:3)                                                   
      at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)                                                
                                                                                                                        
                                                                                                                        
  Input:                                                                                                                
  $(function () {                                                                                                       
      var $modal = $('.modal');                                                                                         
      $modal.on('show.bs.modal', function () {                                                                          
          $('body').addClass("modal-open-noscroll");                                                                    
      });                                                                                                               
                                                                                                                        
      $modal.on('hidden.bs.modal', function () {                                                                        
          $('body').removeClass("modal-open-noscroll");                                                                 
      });                                                                                                               
  });                                                                                                                   
                                                                                                                        
  $.fn.findName = function (name) {                                                                                     
      return $(this).find('[name='+name+']');                                                                           
  };                                                                                                                    
                                                                                                                        
  $.fn.nameVal = function (name) {                                                                                      
      return $(this).findName(name).val();                                                                              
  };                                                                                                                    
                                                                                                                        
  $.fn.onPjax = function(event, $target, callback) {                                                                    
    $(this).off(event, $target);                                                                                        
    $(this).on(event, $target, callback);                                                                               
  };                                                                                                                    
                                                                                                                        
  $.extend({                                                                                                            
      round: function (value, precision) {                                                                              
          if (precision === undefined) {                                                                                
              precision = 2;                                                                                            
          }                                                                                                             
                                                                                                                        
          var times = Math.pow(10, precision);                                                                          
                                                                                                                        
          return Math.round(value * times) / times                                                                      
      }                                                                                                                 
  });                                                                                                                   
                                                                                                                        
  /**                                                                                                                   
   *                                                                                                                    
   * @param name 插件名称                                                                                               
   * @param callback 插件加载完后执行的函数                                                                             
   * @param refresh 重复获取时执行的函数                                                                                
   * @returns {*}                                                                                                       
   */                                                                                                                   
  window.YesknPlugins.get = function (name, callback, refresh) {                                                        
      const self = window.YesknPlugins;                                                                                 
                                                                                                                        
      if (self[name].initialized === true) {                                                                            
          if (refresh) refresh(self[name].result);                                                                      
          if (callback) self[name].result = callback(eval(self[name].identifier));                                      
          return self[name];                                                                                            
      }                                                                                                                 
                                                                                                                        
      const scripts = self[name].scripts;                                                                               
      const links = self[name].links;                                                                                   
                                                                                                                        
      for (const key in scripts) {                                                                                      
          let scriptElm = document.createElement('script');                                                             
          if (scripts.hasOwnProperty(key)) {                                                                            
              scriptElm.setAttribute('src', scripts[key]);                                                              
              document.getElementsByTagName('head')[0].insertBefore(scriptElm, null);                                   
          }                                                                                                             
                                                                                                                        
          if (key * 1 === scripts.length - 1) {                                                                         
              scriptElm.onload = function () {                                                                          
                  if (callback) self[name].result = callback(eval(self[name].identifier));                              
              };                                                                                                        
          }                                                                                                             
      }                                                                                                                 
                                                                                                                        
      for (const key in links) {                                                                                        
          let linkElm = document.createElement('link');                                                                 
          if (links.hasOwnProperty(key)) {                                                                              
              linkElm.setAttribute('href', links[key]);                                                                 
              linkElm.setAttribute('rel', 'stylesheet');                                                                
              document.getElementsByTagName('head')[0].insertBefore(linkElm, null);                                     
          }                                                                                                             
      }                                                                                                                 
                                                                                                                        
      self[name].initialized = true;                                                                                    
                                                                                                                        
      return self[name];                                                                                                
  };

**Comment by Frandore** [comment]
解决了，非全局装了一个uglifyjs，然后用了这个地址就行了，不过问题又来了。
![image](https://user-images.githubusercontent.com/43910740/55238424-72a87180-526f-11e9-9ca5-8a366d25d97a.png)，这个地址不存在？？？？？app下面并没有/web之后的东西。bootstrap.min.css网上找了一个，但是不知道放哪里，这个规则是不是得改一下？

**Comment by Frandore** [comment]
已解决，我眼瞎。

**Comment by Jaggle** [comment]
= =

**Comment by tuciyuan** [comment]
老哥我也遇到.css文件不存在的问题，你怎么解决的？
我进“..”这个隐藏文件夹里创建不了bootsrap目录
