### ISSUE TITLE
建议加一个图片上传发送功能。

### ISSUE THREAD

**Issue by Frandore** [yeskn-studio/vmoex-framework#12]

**Comment by Jaggle** [comment]
这个功能即将发布，已经做好了

**Comment by Frandore** [comment]
> 这个功能即将发布，已经做好了
那太好了。

**Comment by Frandore** [comment]
> 这个功能即将发布，已经做好了

你好，我今天又试了一下。不是我的错，是新的版本确实装不上去= =。
我装了v2.2.0后才装上去了....但是现在的问题是后台打不开，后台：网站/admin 这样打不开。
可否给个联系方式，我想自己微改动网站。以及提议一些改进。

**Comment by Jaggle** [comment]
我的微信：singviy
