### ISSUE TITLE
关于站 数据库 分离

### ISSUE THREAD

**Issue by ZBrettonYe** [yeskn-studio/vmoex-framework#19]
请问这个版本是不是不支持 数据库 和 站点不在一个服务器上？

**Comment by Jaggle** [comment]
支持

**Comment by ZBrettonYe** [comment]
我在跑sudo -u www  php bin/console cache:clear --env=prod
这个的时候
出现报错
In AbstractConnection.php line 155:
                                                          
  Cannot assign requested address [tcp://localhost:6379]
