### ISSUE TITLE
前/后台js css丢失

### ISSUE THREAD

**Issue by xiaohuo-desu** [yeskn-studio/vmoex-framework#24]
![_A`04}IO{6 BPX~SK)MINFE](https://user-images.githubusercontent.com/49596040/60380674-f266f780-9a7b-11e9-887e-b5d04a804a83.png)
![M}3627Z4E4L5 KUH5}ZJE7T](https://user-images.githubusercontent.com/49596040/60380675-f266f780-9a7b-11e9-9156-947ed3c14553.png)

按照部署教程中部署完毕后，无法发布内容，后台排版也炸了。
环境：mysql5.6 php7.2 redis5.0.3 Nginx 1.8.1
已正常配置伪静态，socket正常启动，创建了静态资源

**Comment by xiaohuo-desu** [comment]
配置文档：
# This file is auto-generated during the composer install
parameters:
    database_host: 127.0.0.1
    database_port: 3306
    database_name: xiaohuo
    database_user: xiaohuo
    database_password: yFZZKsrziWmbHyyT
    redis_dsn: 'redis://1178035823@localhost'
    mailer_transport: smtp
    mailer_host: null
    mailer_user: null
    mailer_password: null
    secret: i9did8d9Jd8dhs0dkw8d7djKN8dA071A
    node_path: /usr/bin/node
    uglifyjs2_path: /usr/bin/uglifyjs
    socket_host: 'http://13.115.29.233:3120'
    socket_local_cert: null
    socket_local_pk: null
    socket_push_host: 'http://13.115.29.233:3121'
    assets_base_url: 'http://13.115.29.233'
    github_client_id: null
    github_client_secret: null
    github_redirect_url: null
    baidu_trans.appid: null
    baidu_trans.key: null

**Comment by xiaohuo-desu** [comment]
# This file is auto-generated during the composer install
parameters:
    database_host: 127.0.0.1
    database_port: 3306
    database_name: xiaohuo
    database_user: xiaohuo
    database_password: XXXXXXX
    redis_dsn: 'redis://XXXXXXXX@localhost'
    mailer_transport: smtp
    mailer_host: null
    mailer_user: null
    mailer_password: null
    secret: i9did8d9Jd8dhs0dkw8d7djKN8dA071A
    node_path: /usr/bin/node
    uglifyjs2_path: /usr/bin/uglifyjs
    socket_host: 'http://13.115.29.233:3120'
    socket_local_cert: null
    socket_local_pk: null
    socket_push_host: 'http://13.115.29.233:3121'
    assets_base_url: 'http://13.115.29.233'
    github_client_id: null
    github_client_secret: null
    github_redirect_url: null
    baidu_trans.appid: null
    baidu_trans.key: null

**Comment by xiaohuo-desu** [comment]
创建静态资源文件时曾遇到过这个报错：
![L@@G1@_K)J48)8%UWP3C_{N](https://user-images.githubusercontent.com/49596040/60380844-9651a280-9a7e-11e9-83fe-71c6bc396a5c.png)
![U)@C@C4U1Z`ETSQ 0U2PYMG](https://user-images.githubusercontent.com/49596040/60380847-981b6600-9a7e-11e9-8b6b-bd960976f64d.png)

**Comment by xiaohuo-desu** [comment]
log中其中一段报错：
180.163.220.4 - - [29/Jun/2019:14:56:26 +0800] "GET /login HTTP/1.1" 200 5049 "-" "Mozilla/5.0 (Linux; U; Android 8.1.0; zh-CN; EML-AL00 Build/HUAWEIEML-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 baidu.sogo.uc.UCBrowser/11.9.4.974 UWS/2.13.1.48 Mobile Safari/537.36 AliApp(DingTalk/4.5.11) com.alibaba.android.rimet/10487439 Channel/227200 language/zh-CN"
180.163.220.5 - - [29/Jun/2019:14:56:40 +0800] "GET /build/js/a5bb693.js?v=5d170b7a HTTP/1.1" 404 308 "http://13.115.29.233/login" "Mozilla/5.0 (Linux; U; Android 8.1.0; zh-CN; EML-AL00 Build/HUAWEIEML-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 baidu.sogo.uc.UCBrowser/11.9.4.974 UWS/2.13.1.48 Mobile Safari/537.36 AliApp(DingTalk/4.5.11) com.alibaba.android.rimet/10487439 Channel/227200 language/zh-CN"
180.163.220.5 - - [29/Jun/2019:14:56:43 +0800] "GET /pointer.cur HTTP/1.1" 200 4286 "http://13.115.29.233/build/css/de6acdf.css?v=5d170b7a" "Mozilla/5.0 (Linux; U; Android 8.1.0; zh-CN; EML-AL00 Build/HUAWEIEML-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 baidu.sogo.uc.UCBrowser/11.9.4.974 UWS/2.13.1.48 Mobile Safari/537.36 AliApp(DingTalk/4.5.11) com.alibaba.android.rimet/10487439 Channel/227200 language/zh-CN"
180.163.220.68 - - [29/Jun/2019:14:56:43 +0800] "GET /assets/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18028 "http://13.115.29.233/build/css/de6acdf.css?v=5d170b7a" "Mozilla/5.0 (Linux; U; Android 8.1.0; zh-CN; EML-AL00 Build/HUAWEIEML-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 baidu.sogo.uc.UCBrowser/11.9.4.974 UWS/2.13.1.48 Mobile Safari/537.36 AliApp(DingTalk/4.5.11) com.alibaba.android.rimet/10487439 Channel/227200 language/zh-CN"
180.163.220.4 - - [29/Jun/2019:14:56:44 +0800] "GET /assets/lib/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77160 "http://13.115.29.233/build/css/de6acdf.css?v=5d170b7a" "Mozilla/5.0 (Linux; U; Android 8.1.0; zh-CN; EML-AL00 Build/HUAWEIEML-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 baidu.sogo.uc.UCBrowser/11.9.4.974 UWS/2.13.1.48 Mobile Safari/537.36 AliApp(DingTalk/4.5.11) com.alibaba.android.rimet/10487439 Channel/227200 language/zh-CN"

**Comment by Jaggle** [comment]
uglify需要使用es版本，否则不能支持es6的语法，我看了其实是const关键字在es5中没有的原因，请看这一行：https://github.com/yeskn-studio/vmoex-framework/blob/master/app/config/parameters.yml.dist#L27

**Comment by xiaohuo-desu** [comment]
已恢复正常
![HOV`3CC75V94`93`90}EUAW](https://user-images.githubusercontent.com/49596040/60383515-5dc4bf80-9aa4-11e9-9ffd-535df7162adc.jpg)
