### ISSUE TITLE
Fatal error: Allowed memory size

### ISSUE THREAD

**Issue by DaedalusT** [yeskn-studio/vmoex-framework#25]
![QQ截图20190814022950.jpg](https://i.loli.net/2019/08/14/5fkO4GyEVF7qcg2.jpg)
我查看了报错的文件，可惜没什么解决的头绪
服务器是2G2H，PHP版本7.2

**Comment by Jaggle** [comment]
你分配给php的内存只有128M，你可以在php.ini中重新设置memory_limit的值，有些console操作可能比较吃内存。
