### ISSUE TITLE
请问项目还在维护吗  如何在列表页面调用帖内的图片显示在列表页？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [yeskn-studio/vmoex-framework#43]

**Comment by jjsty1e** [comment]
抱歉，暂时不维护了，打算用laravel重写一个版本

**Comment by Yakumo-Yukari** [comment]
> 抱歉，暂时不维护了，打算用laravel重写一个版本

哦哦  laravel版本还会开源吗？

**Comment by jjsty1e** [comment]
会

**Comment by Yakumo-Yukari** [comment]
> 会

好的  期待下新版本的社区  话说预计会在什么时候发布呢？

前端推荐 参考下这2个社区  感觉布局还不错
[https://eleduck.com/](https://eleduck.com/)

[https://www.zfrontier.com/](https://www.zfrontier.com/)

**Comment by jjsty1e** [comment]
感谢提供参考~
