### ISSUE TITLE
打开之后

### ISSUE THREAD

**Issue by NoviceLevel** [yeskn-studio/vmoex-framework#44]
Parse error: syntax error, unexpected ':', expecting ';' or '{' in /www/wwwroot/zzzacg.xyz/src/Yeskn/MainBundle/Entity/User.php on line 751
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Fatal error: Uncaught exception 'Doctrine\ORM\Mapping\MappingException' with message 'The target-entity Yeskn\MainBundle\Entity\User cannot be found in 'Yeskn\MainBundle\Entity\Visit#user'.' in /www/wwwroot/zzzacg.xyz/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:762 Stack trace: #0 /www/wwwroot/zzzacg.xyz/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php(1028): Doctrine\ORM\Mapping\MappingException::invalidTargetEntityClass('Yeskn\\MainBundl...', 'Yeskn\\MainBundl...', 'user') #1 /www/wwwroot/zzzacg.xyz/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(272): Doctrine\ORM\Mapping\ClassMetadataInfo->validateAssociations() #2 /www/wwwroot/zzzacg.xyz/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(251): Doctrine\ORM\Mapping\ClassMetadataFactory->validateRuntimeMetadata(Object(Doctrine\ORM\Mapping\ClassMetadata), NULL) #3 /www/wwwroot/zzzacg.xyz/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php(332): Do in /www/wwwroot/zzzacg.xyz/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php on line 762

**Comment by jjsty1e** [comment]
请用php7以上版本
