### ISSUE TITLE
作者问下是否可以使用你的程序来搭建社区呢

### ISSUE THREAD

**Issue by Yakumo-Yukari** [yeskn-studio/vmoex-framework#6]
作者问下是否可以使用你的程序来搭建社区呢？

**Comment by Jaggle** [comment]
😅可以的，代码写的比较随意，有空我整理整理出个RC版，应该是基于MIT协议的。

**Comment by Yakumo-Yukari** [comment]
谢谢～期待一下RC版本

**Comment by Yakumo-Yukari** [comment]
大佬有空了可以readme里写个安装步骤说明吗

**Comment by Jaggle** [comment]
hi，readme写好了...，抱歉这么晚才写好，因为这个真的是需要整理+自己亲自从零安装一遍，真的是非非非非常的麻烦  - -，请勿嫌弃~

**Comment by Yakumo-Yukari** [comment]
@Jaggle 23333 谢谢了
